In [3]:
import pandas as pd
df1 = pd.DataFrame(
    {
        "key": ["ко", "K1", "K2", "K3"], "Α": ["ΑΘ", "A1", "A2", "A3"], "в": ["ве", "81", "B2", "83"],
    }
)
df2 = pd.DataFrame(
    {
    "key": ["ко", "KI", "K5", "K6"], "C": ["CO", "C1", "C2", "C3"], "D": ["DO", "D1", "D2", "D3"],
    }
)

In [4]:
df1

  key   Α   в
0  ко  ΑΘ  ве
1  K1  A1  81
2  K2  A2  B2
3  K3  A3  83

In [5]:
df2

  key   C   D
0  ко  CO  DO
1  KI  C1  D1
2  K5  C2  D2
3  K6  C3  D3

In [6]:
pd.merge(df1,df2)

  key   Α   в   C   D
0  ко  ΑΘ  ве  CO  DO

In [8]:
### inner join
pd.merge(df1,df2,on="key",how='inner')

  key   Α   в   C   D
0  ко  ΑΘ  ве  CO  DO

In [12]:
### left join
pd.merge(df1,df2,how='left',on="key")

  key   Α   в    C    D
0  ко  ΑΘ  ве   CO   DO
1  K1  A1  81  NaN  NaN
2  K2  A2  B2  NaN  NaN
3  K3  A3  83  NaN  NaN

In [13]:
### right join
pd.merge(df1,df2,how='right',on="key")

  key    Α    в   C   D
0  ко   ΑΘ   ве  CO  DO
1  KI  NaN  NaN  C1  D1
2  K5  NaN  NaN  C2  D2
3  K6  NaN  NaN  C3  D3

In [14]:
### outer join
pd.merge(df1,df2,how='outer',on="key")

  key    Α    в    C    D
0  K1   A1   81  NaN  NaN
1  K2   A2   B2  NaN  NaN
2  K3   A3   83  NaN  NaN
3  K5  NaN  NaN   C2   D2
4  K6  NaN  NaN   C3   D3
5  KI  NaN  NaN   C1   D1
6  ко   ΑΘ   ве   CO   DO

In [15]:
### left outer join
pd.merge(df1,df2,how='outer',on="key",indicator=True)

  key    Α    в    C    D      _merge
0  K1   A1   81  NaN  NaN   left_only
1  K2   A2   B2  NaN  NaN   left_only
2  K3   A3   83  NaN  NaN   left_only
3  K5  NaN  NaN   C2   D2  right_only
4  K6  NaN  NaN   C3   D3  right_only
5  KI  NaN  NaN   C1   D1  right_only
6  ко   ΑΘ   ве   CO   DO        both

In [17]:
df2.shape

(4, 3)

In [18]:
df1.shape

(4, 3)

In [19]:
### cross join

In [20]:
pd.merge(df1,df2,how='cross')

   key_x   Α   в key_y   C   D
0     ко  ΑΘ  ве    ко  CO  DO
1     ко  ΑΘ  ве    KI  C1  D1
2     ко  ΑΘ  ве    K5  C2  D2
3     ко  ΑΘ  ве    K6  C3  D3
4     K1  A1  81    ко  CO  DO
5     K1  A1  81    KI  C1  D1
6     K1  A1  81    K5  C2  D2
7     K1  A1  81    K6  C3  D3
8     K2  A2  B2    ко  CO  DO
9     K2  A2  B2    KI  C1  D1
10    K2  A2  B2    K5  C2  D2
11    K2  A2  B2    K6  C3  D3
12    K3  A3  83    ко  CO  DO
13    K3  A3  83    KI  C1  D1
14    K3  A3  83    K5  C2  D2
15    K3  A3  83    K6  C3  D3

In [21]:
pd.merge(df1,df2,how='cross').shape

(16, 6)