In [1]:
import pandas as pd

In [8]:
pd.read_csv("/Users/apple/Downloads/extracted_data.csv")

,Sales,Units,Transactions,Gross Profits,Customers,Promotions(Yes/No),Location,Days
0,701.0,49,38,37,99,Yes,Bangalore,Day 1
1,807.0,73,14,81,81,Yes,Bangalore,Day 2
2,743.0,23,75,38,40,Yes,Bangalore,Day 3
3,347.0,85,82,74,32,Yes,Bangalore,Day 4
4,275.0,100,10,83,43,Yes,Bangalore,Day 5
5,397.0,35,38,68,28,No,Bangalore,Day 6
6,744.0,14,64,41,73,Yes,Bangalore,Day 7
7,519.0,47,78,17,11,No,Chennai,Day 1
8,822.0,11,33,87,89,No,Chennai,Day 2
9,138.0,46,97,14,61,No,Chennai,Day 3
10,652.0,92,74,67,97,Yes,Chennai,Day 4
11,410.0,56,50,30,66,Yes,Chennai,Day 5
12,879.0,79,18,33,21,No,Chennai,Day 6
13,255.0,72,52,37,61,Yes,Chennai,Day 7
14,122.0,64,27,28,78,No,Hyderabad,Day 1
15,453.0,58,28,36,53,No,Hyderabad,Day 2
16,746.0,72,78,29,46,No,Hyderabad,Day 3
17,962.0,20,15,29,57,Yes,Hyderabad,Day 4
18,436.0,47,54,87,70,Yes,Hyderabad,Day 5
19,132.0,52,62,57,90,No,Hyderabad,Day 6
20,131.0,15,37,43,16,Yes,Hyderabad,Day 7
21,631.0,80,96,73,75,Yes,Mumbai,Day 1
22,NaN,953,52,65,32,Yes,Mumbai,Day 2
23,105.0,70,16,84,18,Yes,Mumbai,Day 3
24,236.0,34,87,54,41,Yes,Mumbai,Day 4
25,402.0,24,84,85,67,Yes,Mumbai,Day 5
26,543.0,77,37,68,11,No,Mumbai,Day 6
27,622.0,13,73,25,24,Yes,Mumbai,Day 7

In [9]:
sales_df = pd.read_csv("/Users/apple/Downloads/extracted_data.csv")

In [10]:
sales_df

,Sales,Units,Transactions,Gross Profits,Customers,Promotions(Yes/No),Location,Days
0,701.0,49,38,37,99,Yes,Bangalore,Day 1
1,807.0,73,14,81,81,Yes,Bangalore,Day 2
2,743.0,23,75,38,40,Yes,Bangalore,Day 3
3,347.0,85,82,74,32,Yes,Bangalore,Day 4
4,275.0,100,10,83,43,Yes,Bangalore,Day 5
5,397.0,35,38,68,28,No,Bangalore,Day 6
6,744.0,14,64,41,73,Yes,Bangalore,Day 7
7,519.0,47,78,17,11,No,Chennai,Day 1
8,822.0,11,33,87,89,No,Chennai,Day 2
9,138.0,46,97,14,61,No,Chennai,Day 3
10,652.0,92,74,67,97,Yes,Chennai,Day 4
11,410.0,56,50,30,66,Yes,Chennai,Day 5
12,879.0,79,18,33,21,No,Chennai,Day 6
13,255.0,72,52,37,61,Yes,Chennai,Day 7
14,122.0,64,27,28,78,No,Hyderabad,Day 1
15,453.0,58,28,36,53,No,Hyderabad,Day 2
16,746.0,72,78,29,46,No,Hyderabad,Day 3
17,962.0,20,15,29,57,Yes,Hyderabad,Day 4
18,436.0,47,54,87,70,Yes,Hyderabad,Day 5
19,132.0,52,62,57,90,No,Hyderabad,Day 6
20,131.0,15,37,43,16,Yes,Hyderabad,Day 7
21,631.0,80,96,73,75,Yes,Mumbai,Day 1
22,NaN,953,52,65,32,Yes,Mumbai,Day 2
23,105.0,70,16,84,18,Yes,Mumbai,Day 3
24,236.0,34,87,54,41,Yes,Mumbai,Day 4
25,402.0,24,84,85,67,Yes,Mumbai,Day 5
26,543.0,77,37,68,11,No,Mumbai,Day 6
27,622.0,13,73,25,24,Yes,Mumbai,Day 7

In [11]:
### columns rows and inbuilt functions that subsetting data

In [12]:
sales_df.head()

,Sales,Units,Transactions,Gross Profits,Customers,Promotions(Yes/No),Location,Days
0,701.0,49,38,37,99,Yes,Bangalore,Day 1
1,807.0,73,14,81,81,Yes,Bangalore,Day 2
2,743.0,23,75,38,40,Yes,Bangalore,Day 3
3,347.0,85,82,74,32,Yes,Bangalore,Day 4
4,275.0,100,10,83,43,Yes,Bangalore,Day 5

In [13]:
sales_df.tail()

,Sales,Units,Transactions,Gross Profits,Customers,Promotions(Yes/No),Location,Days
23,105.0,70,16,84,18,Yes,Mumbai,Day 3
24,236.0,34,87,54,41,Yes,Mumbai,Day 4
25,402.0,24,84,85,67,Yes,Mumbai,Day 5
26,543.0,77,37,68,11,No,Mumbai,Day 6
27,622.0,13,73,25,24,Yes,Mumbai,Day 7

In [14]:
sales_df['Sales']

0     701.0
1     807.0
2     743.0
3     347.0
4     275.0
5     397.0
6     744.0
7     519.0
8     822.0
9     138.0
10    652.0
11    410.0
12    879.0
13    255.0
14    122.0
15    453.0
16    746.0
17    962.0
18    436.0
19    132.0
20    131.0
21    631.0
22      NaN
23    105.0
24    236.0
25    402.0
26    543.0
27    622.0
Name: Sales, dtype: float64

In [15]:
sales_df['Location'].head()

0    Bangalore
1    Bangalore
2    Bangalore
3    Bangalore
4    Bangalore
Name: Location, dtype: str

In [18]:
sales_df[['Location','Units','Customers']]

     Location  Units  Customers
0   Bangalore     49         99
1   Bangalore     73         81
2   Bangalore     23         40
3   Bangalore     85         32
4   Bangalore    100         43
5   Bangalore     35         28
6   Bangalore     14         73
7     Chennai     47         11
8     Chennai     11         89
9     Chennai     46         61
10    Chennai     92         97
11    Chennai     56         66
12    Chennai     79         21
13    Chennai     72         61
14  Hyderabad     64         78
15  Hyderabad     58         53
16  Hyderabad     72         46
17  Hyderabad     20         57
18  Hyderabad     47         70
19  Hyderabad     52         90
20  Hyderabad     15         16
21     Mumbai     80         75
22     Mumbai    953         32
23     Mumbai     70         18
24     Mumbai     34         41
25     Mumbai     24         67
26     Mumbai     77         11
27     Mumbai     13         24

In [19]:
sales_df[['Location','Units','Customers']].head()

    Location  Units  Customers
0  Bangalore     49         99
1  Bangalore     73         81
2  Bangalore     23         40
3  Bangalore     85         32
4  Bangalore    100         43

In [21]:
sales_df[0:8]

,Sales,Units,Transactions,Gross Profits,Customers,Promotions(Yes/No),Location,Days
0,701.0,49,38,37,99,Yes,Bangalore,Day 1
1,807.0,73,14,81,81,Yes,Bangalore,Day 2
2,743.0,23,75,38,40,Yes,Bangalore,Day 3
3,347.0,85,82,74,32,Yes,Bangalore,Day 4
4,275.0,100,10,83,43,Yes,Bangalore,Day 5
5,397.0,35,38,68,28,No,Bangalore,Day 6
6,744.0,14,64,41,73,Yes,Bangalore,Day 7
7,519.0,47,78,17,11,No,Chennai,Day 1

In [22]:
sales_df[10:15]

,Sales,Units,Transactions,Gross Profits,Customers,Promotions(Yes/No),Location,Days
10,652.0,92,74,67,97,Yes,Chennai,Day 4
11,410.0,56,50,30,66,Yes,Chennai,Day 5
12,879.0,79,18,33,21,No,Chennai,Day 6
13,255.0,72,52,37,61,Yes,Chennai,Day 7
14,122.0,64,27,28,78,No,Hyderabad,Day 1

In [23]:
### general purpose inbuilt function

In [24]:
sales_df.columns

Index(['Sales', 'Units', 'Transactions', 'Gross Profits', 'Customers',
       'Promotions(Yes/No)', 'Location', 'Days'],
      dtype='str')

In [25]:
sales_df.index

RangeIndex(start=0, stop=28, step=1)

In [27]:
sales_df['Sales'].min()

np.float64(105.0)

In [29]:
sales_df[['Sales','Units']].min()

Sales    105.0
Units     11.0
dtype: float64

In [30]:
sales_df[['Sales','Units']].max()

Sales    962.0
Units    953.0
dtype: float64

In [31]:
sales_df[['Sales','Units']].sum()

Sales    13210.0
Units     2361.0
dtype: float64

In [32]:
sales_df['Sales'].sum()

np.float64(13210.0)

In [33]:
sales_df['Sales'].mean()

np.float64(489.25925925925924)

In [34]:
sales_df = sales_df.head(10)

In [35]:
sales_df

,Sales,Units,Transactions,Gross Profits,Customers,Promotions(Yes/No),Location,Days
0,701.0,49,38,37,99,Yes,Bangalore,Day 1
1,807.0,73,14,81,81,Yes,Bangalore,Day 2
2,743.0,23,75,38,40,Yes,Bangalore,Day 3
3,347.0,85,82,74,32,Yes,Bangalore,Day 4
4,275.0,100,10,83,43,Yes,Bangalore,Day 5
5,397.0,35,38,68,28,No,Bangalore,Day 6
6,744.0,14,64,41,73,Yes,Bangalore,Day 7
7,519.0,47,78,17,11,No,Chennai,Day 1
8,822.0,11,33,87,89,No,Chennai,Day 2
9,138.0,46,97,14,61,No,Chennai,Day 3

In [36]:
sales_df['Sales']

0    701.0
1    807.0
2    743.0
3    347.0
4    275.0
5    397.0
6    744.0
7    519.0
8    822.0
9    138.0
Name: Sales, dtype: float64

In [37]:
sales_df['Sales'].cumsum()

0     701.0
1    1508.0
2    2251.0
3    2598.0
4    2873.0
5    3270.0
6    4014.0
7    4533.0
8    5355.0
9    5493.0
Name: Sales, dtype: float64

In [38]:
sales_df['Sales'].cumprod()

0    7.010000e+02
1    5.657070e+05
2    4.203203e+08
3    1.458511e+11
4    4.010906e+13
5    1.592330e+16
6    1.184693e+19
7    6.148559e+21
8    5.054115e+24
9    6.974679e+26
Name: Sales, dtype: float64

In [39]:
sales_df['Sales'].median()

np.float64(610.0)

In [41]:
sales_df.shape ### return rows and columns

(10, 8)

In [43]:
sales_df.dtypes

Sales                 float64
Units                   int64
Transactions            int64
Gross Profits           int64
Customers               int64
Promotions(Yes/No)        str
Location                  str
Days                      str
dtype: object