In [48]:
import pandas as pd
import numpy as np
import seaborn as sns

In [49]:
df = sns.load_dataset("mpg")

In [50]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [51]:
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10

In [52]:
df.drop("mpg",axis=1,inplace=True)

In [53]:
df.head()

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [54]:
df.drop([0,1],axis=0,inplace=True)

In [55]:
df.head()

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
2,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,8,302.0,140.0,3449,10.5,70,usa,ford torino
5,8,429.0,198.0,4341,10.0,70,usa,ford galaxie 500
6,8,454.0,220.0,4354,9.0,70,usa,chevrolet impala

In [57]:
df.head()

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
2,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,8,302.0,140.0,3449,10.5,70,usa,ford torino
5,8,429.0,198.0,4341,10.0,70,usa,ford galaxie 500
6,8,454.0,220.0,4354,9.0,70,usa,chevrolet impala

In [61]:
df.rename(columns={'cylinders':"cyl"},inplace=True)

In [62]:
df.head()

,cyl,displacement,horsepower,weight,acceleration,model_year,origin,name
2,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,8,302.0,140.0,3449,10.5,70,usa,ford torino
5,8,429.0,198.0,4341,10.0,70,usa,ford galaxie 500
6,8,454.0,220.0,4354,9.0,70,usa,chevrolet impala

In [63]:
df.rename(index={2:"test"}, inplace=True)

In [64]:
df.head()

,cyl,displacement,horsepower,weight,acceleration,model_year,origin,name
test,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,8,302.0,140.0,3449,10.5,70,usa,ford torino
5,8,429.0,198.0,4341,10.0,70,usa,ford galaxie 500
6,8,454.0,220.0,4354,9.0,70,usa,chevrolet impala