In [1]:
import pandas as pd

In [3]:
pd.DataFrame([[300,15,'Yes'],[400,30,'No'],[500,40,'Yes']])

     0   1    2
0  300  15  Yes
1  400  30   No
2  500  40  Yes

In [5]:
pd.DataFrame([[300,15,'Yes'],[400,30,'No'],[500,40,'Yes']],columns=['$Sales','Units','Promotions'],index = ['Jan','Feb','Mar'])

     $Sales  Units Promotions
Jan     300     15        Yes
Feb     400     30         No
Mar     500     40        Yes

In [6]:
### implementing dataframws using list

In [7]:
d = {'Jan':[200,300],'Feb':[300,400]}

In [8]:
d

{'Jan': [200, 300], 'Feb': [300, 400]}

In [9]:
pd.DataFrame(d,index = ['Sales','Customers'])

           Jan  Feb
Sales      200  300
Customers  300  400

In [10]:
### creating dataframe using numpy

In [11]:
import numpy as np

In [14]:
np.random.randint(0,9,(3,3))

array([[3, 4, 1],
       [2, 4, 5],
       [6, 5, 0]])

In [15]:
data = np.random.randint(10,20,(3,3))

In [16]:
data

array([[18, 11, 12],
       [16, 14, 10],
       [14, 17, 11]])

In [17]:
pd.DataFrame(data)

    0   1   2
0  18  11  12
1  16  14  10
2  14  17  11

In [18]:
pd.DataFrame(data,index=['A','B','C'],columns=['X','Y','Z'])

    X   Y   Z
A  18  11  12
B  16  14  10
C  14  17  11