In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import seaborn as sns

In [5]:
df = sns.load_dataset("titanic")

In [6]:
df.index

RangeIndex(start=0, stop=891, step=1)

In [7]:
df.tail()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

In [8]:
df.set_index('alone').head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive
alone,,,,,,,,,,,,,,
False,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no
False,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes
True,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes
False,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes
True,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no

In [9]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [12]:
df.set_index('alone',inplace=True)

In [14]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive
alone,,,,,,,,,,,,,,
False,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no
False,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes
True,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes
False,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes
True,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no

In [16]:
df.reset_index().head()

,alone,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive
0,False,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no
1,False,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes
2,True,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes
3,False,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes
4,True,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no

In [17]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive
alone,,,,,,,,,,,,,,
False,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no
False,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes
True,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes
False,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes
True,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no

In [18]:
df.shape

(891, 14)