In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

In [3]:
df = sns.load_dataset("mpg")

In [4]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [5]:
df.isna()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
393,False,False,False,False,False,False,False,False,False
394,False,False,False,False,False,False,False,False,False
395,False,False,False,False,False,False,False,False,False
396,False,False,False,False,False,False,False,False,False
397,False,False,False,False,False,False,False,False,False

In [6]:
df.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
name            0
dtype: int64

In [7]:
(df.isna().sum()/df.shape[0])*100

mpg             0.000000
cylinders       0.000000
displacement    0.000000
horsepower      1.507538
weight          0.000000
acceleration    0.000000
model_year      0.000000
origin          0.000000
name            0.000000
dtype: float64

In [10]:
df['horsepower'].fillna(df['horsepower'].median(),inplace=True)

/var/folders/n9/klj9bs6j6h175l1xsqhs40n40000gn/T/ipykernel_3299/2669785465.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['horsepower'].fillna(df['horsepower'].median(),inplace=True)

0      130.0
1      165.0
2      150.0
3      150.0
4      140.0
       ...
393     86.0
394     52.0
395     84.0
396     79.0
397     82.0
Name: horsepower, Length: 398, dtype: float64

In [11]:
(df.isna().sum()/df.shape[0])*100

mpg             0.000000
cylinders       0.000000
displacement    0.000000
horsepower      1.507538
weight          0.000000
acceleration    0.000000
model_year      0.000000
origin          0.000000
name            0.000000
dtype: float64

In [13]:
df['horsepower'].fillna(df['horsepower'].median(), inplace=True)
print(df)

      mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0
1    15.0          8         350.0       165.0    3693          11.5
2    18.0          8         318.0       150.0    3436          11.0
3    16.0          8         304.0       150.0    3433          12.0
4    17.0          8         302.0       140.0    3449          10.5
..    ...        ...           ...         ...     ...           ...
393  27.0          4         140.0        86.0    2790          15.6
394  44.0          4          97.0        52.0    2130          24.6
395  32.0          4         135.0        84.0    2295          11.6
396  28.0          4         120.0        79.0    2625          18.6
397  31.0          4         119.0        82.0    2720          19.4

     model_year  origin                       name
0            70     usa  chevrolet chevelle malibu
1            70     usa          buick skylark 320
2            70     usa         plymouth satellite
3            70     usa              amc rebel sst
4            70     usa                ford torino
..          ...     ...                        ...
393          82     usa            ford mustang gl
394          82  europe                  vw pickup
395          82     usa              dodge rampage
396          82     usa                ford ranger
397          82     usa                 chevy s-10

[398 rows x 9 columns]

/var/folders/n9/klj9bs6j6h175l1xsqhs40n40000gn/T/ipykernel_3299/147131728.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['horsepower'].fillna(df['horsepower'].median(), inplace=True)

In [14]:
(df.isna().sum()/df.shape[0])*100

mpg             0.000000
cylinders       0.000000
displacement    0.000000
horsepower      1.507538
weight          0.000000
acceleration    0.000000
model_year      0.000000
origin          0.000000
name            0.000000
dtype: float64

In [17]:
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].median())

In [18]:
(df.isna().sum()/df.shape[0])*100

mpg             0.0
cylinders       0.0
displacement    0.0
horsepower      0.0
weight          0.0
acceleration    0.0
model_year      0.0
origin          0.0
name            0.0
dtype: float64

In [20]:
df=sns.load_dataset("titanic")

In [24]:
df.shape

(891, 15)

In [25]:
df.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [26]:
df.dropna(how='all',axis=0).shape

(891, 15)

In [27]:
df.dropna(how='any',axis=1).shape

(891, 11)

In [28]:
df.dropna(how='all',axis=1).shape

(891, 15)

In [1]:
### cross tabs

In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
df = pd.read_csv("/Users/apple/Downloads/extracted_data.csv")

In [5]:
df.head()

,Sales,Units,Transactions,Gross Profits,Customers,Promotions(Yes/No),Location,Days
0,701.0,49,38,37,99,Yes,Bangalore,Day 1
1,807.0,73,14,81,81,Yes,Bangalore,Day 2
2,743.0,23,75,38,40,Yes,Bangalore,Day 3
3,347.0,85,82,74,32,Yes,Bangalore,Day 4
4,275.0,100,10,83,43,Yes,Bangalore,Day 5

In [6]:
pd.crosstab(df['Location'],df['Days'])

Days       Day 1  Day 2  Day 3  Day 4  Day 5  Day 6  Day 7
Location
Bangalore      1      1      1      1      1      1      1
Chennai        1      1      1      1      1      1      1
Hyderabad      1      1      1      1      1      1      1
Mumbai         1      1      1      1      1      1      1

In [8]:
pd.crosstab(df['Location'],[df['Days'],df['Promotions(Yes/No)']])

Days               Day 1     Day 2     Day 3     Day 4 Day 5 Day 6 Day 7
Promotions(Yes/No)    No Yes    No Yes    No Yes   Yes   Yes    No   Yes
Location
Bangalore              0   1     0   1     0   1     1     1     1     1
Chennai                1   0     1   0     1   0     1     1     1     1
Hyderabad              1   0     1   0     1   0     1     1     1     1
Mumbai                 0   1     0   1     0   1     1     1     1     1

In [9]:
### cut method

In [10]:
df

,Sales,Units,Transactions,Gross Profits,Customers,Promotions(Yes/No),Location,Days
0,701.0,49,38,37,99,Yes,Bangalore,Day 1
1,807.0,73,14,81,81,Yes,Bangalore,Day 2
2,743.0,23,75,38,40,Yes,Bangalore,Day 3
3,347.0,85,82,74,32,Yes,Bangalore,Day 4
4,275.0,100,10,83,43,Yes,Bangalore,Day 5
5,397.0,35,38,68,28,No,Bangalore,Day 6
6,744.0,14,64,41,73,Yes,Bangalore,Day 7
7,519.0,47,78,17,11,No,Chennai,Day 1
8,822.0,11,33,87,89,No,Chennai,Day 2
9,138.0,46,97,14,61,No,Chennai,Day 3
10,652.0,92,74,67,97,Yes,Chennai,Day 4
11,410.0,56,50,30,66,Yes,Chennai,Day 5
12,879.0,79,18,33,21,No,Chennai,Day 6
13,255.0,72,52,37,61,Yes,Chennai,Day 7
14,122.0,64,27,28,78,No,Hyderabad,Day 1
15,453.0,58,28,36,53,No,Hyderabad,Day 2
16,746.0,72,78,29,46,No,Hyderabad,Day 3
17,962.0,20,15,29,57,Yes,Hyderabad,Day 4
18,436.0,47,54,87,70,Yes,Hyderabad,Day 5
19,132.0,52,62,57,90,No,Hyderabad,Day 6
20,131.0,15,37,43,16,Yes,Hyderabad,Day 7
21,631.0,80,96,73,75,Yes,Mumbai,Day 1
22,NaN,953,52,65,32,Yes,Mumbai,Day 2
23,105.0,70,16,84,18,Yes,Mumbai,Day 3
24,236.0,34,87,54,41,Yes,Mumbai,Day 4
25,402.0,24,84,85,67,Yes,Mumbai,Day 5
26,543.0,77,37,68,11,No,Mumbai,Day 6
27,622.0,13,73,25,24,Yes,Mumbai,Day 7

In [11]:
df['Sales'].min(),df['Sales'].max()

(np.float64(105.0), np.float64(962.0))

In [14]:
cutData = pd.cut(df['Sales'],3)

In [15]:
cutData

0       (676.333, 962.0]
1       (676.333, 962.0]
2       (676.333, 962.0]
3     (104.143, 390.667]
4     (104.143, 390.667]
5     (390.667, 676.333]
6       (676.333, 962.0]
7     (390.667, 676.333]
8       (676.333, 962.0]
9     (104.143, 390.667]
10    (390.667, 676.333]
11    (390.667, 676.333]
12      (676.333, 962.0]
13    (104.143, 390.667]
14    (104.143, 390.667]
15    (390.667, 676.333]
16      (676.333, 962.0]
17      (676.333, 962.0]
18    (390.667, 676.333]
19    (104.143, 390.667]
20    (104.143, 390.667]
21    (390.667, 676.333]
22                   NaN
23    (104.143, 390.667]
24    (104.143, 390.667]
25    (390.667, 676.333]
26    (390.667, 676.333]
27    (390.667, 676.333]
Name: Sales, dtype: category
Categories (3, interval[float64, right]): [(104.143, 390.667] < (390.667, 676.333] < (676.333, 962.0]]

In [16]:
df['cutData']=cutData

In [17]:
df[['Sales','cutData']].head()

   Sales             cutData
0  701.0    (676.333, 962.0]
1  807.0    (676.333, 962.0]
2  743.0    (676.333, 962.0]
3  347.0  (104.143, 390.667]
4  275.0  (104.143, 390.667]

In [23]:
cutData_labels = pd.cut(df['Sales'],3,labels=['Low','Medium','High'])

In [24]:
df['cutData_labels'] = cutData_labels

In [26]:
df[['Sales','cutData','cutData_labels']].head(10)

   Sales             cutData cutData_labels
0  701.0    (676.333, 962.0]           High
1  807.0    (676.333, 962.0]           High
2  743.0    (676.333, 962.0]           High
3  347.0  (104.143, 390.667]            Low
4  275.0  (104.143, 390.667]            Low
5  397.0  (390.667, 676.333]         Medium
6  744.0    (676.333, 962.0]           High
7  519.0  (390.667, 676.333]         Medium
8  822.0    (676.333, 962.0]           High
9  138.0  (104.143, 390.667]            Low